# Site settings
title: Irina Ivanova Profile Page
email: irina.ivanova@protonmail.com
description: >-
  Irina Ivanova is an expirienced tester and a junior developer in Estonia.
  Programming languages: JavaScript, Python, Bash, HTML, CSS
baseurl: ""
url: "http://127.0.0.1:4000"
github_username: iriiiina

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8
