# Site settings
title: Irina Ivanova Profile Page
email: irina.ivanova@protonmail.com
description: >-
  Irina Ivanova is an expirienced tester and a junior developer in Estonia.
  Programming languages: JavaScript, Python, Bash, HTML, CSS
baseurl: ""
url: "http://127.0.0.1:4000"
github_username: iriiiina

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8
