name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.1
    - name: Ping URL
      uses: nerdify/ping-action@1.0.0
